version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    links:
      - database
    networks:
      - ylab_rest_network

  database:
    image: postgres:15.1-alpine
    restart: always
    container_name: database
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - ylab_rest_network


networks:
  ylab_rest_network:
    name: ylab_rest_network
volumes:
  database:
    name: database